---

- name: Install a .deb package from the internet
  ansible.builtin.apt:
    deb: "https://github.com/openbao/openbao/releases/download/v{{openbao_version}}/bao_{{openbao_version}}_{{ansible_system | lower}}_{{_openbao_architecture_options[ansible_userspace_architecture]}}.{{_openbao_pkg_extension}}"

- name: Generate openbao config
  ansible.builtin.template:
    src: config.j2
    dest: /etc/openbao/openbao.hcl
    mode: '0640'
  notify: restart openbao

- name: Enable openbao service
  ansible.builtin.service:
    name: openbao
    enabled: true